from flou_import import *

type_terrain = Classe_classification("type_terrain", "peu escarpe", "escarpe")
accessibilite = Classe_classification("accessibilite", "peu accessible", "moyennement accessible", "accessible")
ressenti = Classe_classification("ressenti", "favorable", "defavorable")
couleur_eau = Classe_classification("couleur de l'eau", "claire", "trouble")
odeur_eau = Classe_classification("odeur de l'eau", "pas d'odeur", "odeur", "forte odeur")

difference_distance = Classe("difference distance")
diff_dist_faible = IFT(0, 0, 200, 900, 1, "faible")
diff_dist_moyenne = IFT(300, 900, 1000, 1600, 1, "moyenne")
diff_dist_elevee = IFT(1000, 1600, 1800, 1800, 1, "elevee")
difference_distance.ajouter(diff_dist_faible, diff_dist_moyenne, diff_dist_elevee)
difference_distance.plot()

difference_altitude = Classe("difference altitude")
diff_alt_faible = IFT(0, 0, 1000, 1500, 1, "faible")
diff_alt_moyenne = IFT(1000, 1500, 2500, 3000, 1, "moyenne")
diff_alt_elevee = IFT(2500, 3000, 4500, 4500, 1, "elevee")
difference_altitude.ajouter(diff_alt_faible, diff_alt_moyenne, diff_alt_elevee)
difference_altitude.plot()

altitude_cumulee = Classe("altitude cumulee totale")
alt_cum_faible = IFT(0, 0, 5000, 7000, 1, "faible")
alt_cum_moyenne = IFT(5000, 7000, 10000, 15000, 1, "moyenne")
alt_cum_elevee = IFT(10000, 15000, 20000, 20000, 1, "elevee")
altitude_cumulee.ajouter(alt_cum_faible,alt_cum_moyenne, alt_cum_elevee)
altitude_cumulee.plot()

somme_sources_besoins = Classe("proportion entre les sources et les besoins")
src_besoin_trop_peu = IFT(0, 0, 0.4, 0.7, 1, "beaucoup trop peu" )
src_besoin_peu = IFT(0.4, 0.7,0.9, 1, 1, "peu" )
src_besoin_assez = IFT(0.9, 1, 1.2, 1.4, 1, "assez" )
src_besoin_trop = IFT(1.2, 1.4,4, 4, 1, "trop")
somme_sources_besoins.ajouter(src_besoin_trop_peu, src_besoin_peu, src_besoin_assez, src_besoin_trop)
somme_sources_besoins.plot()

prop_debit_besoin = Classe("proportion entre le debit de la source et le besoin du village")
prop_trop_faible = IFT(0,0,  0.8, 1,1, "trop faible")
prop_satisf = IFT(0.8, 1, 1.2, 3, 1, "satisfaisant")
prop_trop_elevee = IFT(1.2, 3, 4, 4,1,  "trop elevee")
prop_debit_besoin.ajouter(prop_trop_faible, prop_satisf, prop_trop_elevee)
prop_debit_besoin.plot()